name: garage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dotenv: ^4.2.0
  equatable: ^2.0.7
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.0
  flutter_side_menu: ^0.5.41
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^14.0.2
  go_router: ^16.2.2
  intl: ^0.20.2
  riverpod: ^3.0.0
  shared_preferences: ^2.5.3
  very_good_analysis: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/Roboto-ExtraBold.ttf
            weight: 800

